index:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about

copyright:
    path: /copyright
    controller: App\Controller\DefaultController::copyright

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact